version: "3.4"
services:
    mongodb:
        image: mongo:6.0.3
        container_name: mongo1
        hostname: mongo
        environment:
            HOME: /data/db
        ports:
            - 27017:27017
        volumes:
            - "mongodb:/data/db"
    redis:
        image: redis:7.0.7
        container_name: redis1
        hostname: redis
        ports:
            - 6379:6379
        restart: always
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
        volumes:
            - "redis:/data"
    query_cache:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: query_cache
        hostname: querycache
        ports:
            - 3000:3000
        depends_on:
            - mongodb
            - redis
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
volumes:
    mongodb:
        driver: local
    redis:
        driver: local
